version: "3.9"
services:
  mysql:
    image: mysql
    container_name: bd_mysql_sebas
    ports:
      - "23307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=sebas
      - MYSQL_PASSWORD=sebas
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8807:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
